alter database postgres
set timezone to 'Asia/Ho_Chi_Minh';

create table if not exists pets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  fullName character varying null,
  ownerName character varying null,
  gender smallint null,
  hometown character varying null,
  dateOfBirth date null,
  breed character varying null,
  dateOfIssue date null,
  avatar character varying null,
  authId uuid not null,
  code character varying not null,

  constraint pets_pkey primary key (id),
  constraint pets_code_key unique (code),
  constraint pets_authId_fkey foreign KEY ("authId") references auth.users (id) on delete set null

) TABLESPACE pg_default;
alter table public.pets enable row level security;
create policy "Users can insert their own pets"
  on public.pets
  for insert
  to authenticated
  with check (
    (select auth.uid()) = "authId"
);

create policy "Users can update own pets."
  on pets for update 
  using ((select auth.uid()) = authId);

create policy "Auth user can view another pets."
  on profiles for select
  using (auth.role() = 'authenticated');
