export function useCatBreed() {
  const breeds = [
    {
      key: 'abyssinian',
      value: 'Abyssinian',
      vietnamese: 'Mèo Abyssinian',
      description: 'Giống mèo có nguồn gốc từ Ethiopia với bộ lông màu nâu đỏ đặc trưng và tính cách năng động.',
      id: 0,
    },
    {
      key: 'aegean',
      value: 'Aegean',
      vietnamese: 'Mèo Aegean',
      description: 'Giống mèo tự nhiên của Hy Lạp, nổi tiếng với khả năng bơi lội và bộ lông đa màu.',
      id: 1,
    },
    {
      key: 'american-curl',
      value: 'American Curl',
      vietnamese: 'Mèo American Curl',
      description: 'Đặc trưng bởi đôi tai cong ngược độc đáo và tính cách thân thiện.',
      id: 2,
    },
    {
      key: 'american-bobtail',
      value: 'American Bobtail',
      vietnamese: 'Mèo American Bobtail',
      description: 'Giống mèo có đuôi ngắn tự nhiên, thân thiện và thông minh.',
      id: 3,
    },
    {
      key: 'american-shorthair',
      value: 'American Shorthair',
      vietnamese: 'Mèo American Shorthair',
      description: 'Mèo lông ngắn Mỹ, phổ biến với nhiều màu sắc và tính cách dễ gần.',
      id: 4,
    },
    {
      key: 'american-wirehair',
      value: 'American Wirehair',
      vietnamese: 'Mèo American Wirehair',
      description: 'Đặc trưng bởi bộ lông xoăn cứng, có khả năng thích nghi tốt.',
      id: 5,
    },
    {
      key: 'arabian-mau',
      value: 'Arabian Mau',
      vietnamese: 'Mèo Arabian Mau',
      description: 'Giống mèo tự nhiên từ bán đảo Ả Rập, khỏe mạnh và độc lập.',
      id: 6,
    },
    {
      key: 'australian-mist',
      value: 'Australian Mist',
      vietnamese: 'Mèo Australian Mist',
      description: 'Giống mèo được lai tạo ở Úc, thân thiện và có bộ lông đốm.',
      id: 7,
    },
    {
      key: 'asian',
      value: 'Asian',
      vietnamese: 'Mèo Asian',
      description: 'Nhóm mèo có nguồn gốc từ châu Á, bao gồm nhiều biến thể khác nhau.',
      id: 8,
    },
    {
      key: 'asian-semi-longhair',
      value: 'Asian Semi-longhair',
      vietnamese: 'Mèo Asian Semi-longhair',
      description: 'Mèo lông dài vừa của châu Á, có vẻ ngoài thanh lịch.',
      id: 9,
    },
    {
      key: 'balinese',
      value: 'Balinese',
      vietnamese: 'Mèo Balinese',
      description: 'Phiên bản lông dài của mèo Xiêm, thanh lịch và thông minh.',
      id: 10,
    },
    {
      key: 'bambino',
      value: 'Bambino',
      vietnamese: 'Mèo Bambino',
      description: 'Sự kết hợp giữa Sphynx (không lông) và Munchkin (chân ngắn).',
      id: 11,
    },
    {
      key: 'bengal',
      value: 'Bengal',
      vietnamese: 'Mèo Bengal',
      description: 'Giống mèo lai giữa mèo nhà và mèo báo châu Á, có bộ lông đốm hoang dã, thích nước.',
      id: 12,
    },
    {
      key: 'birman',
      value: 'Birman',
      vietnamese: 'Mèo Birman',
      description: 'Mèo thiêng Birman, có bộ lông dài, đôi mắt xanh và điểm màu đặc trưng.',
      id: 13,
    },
    {
      key: 'bombay',
      value: 'Bombay',
      vietnamese: 'Mèo Bombay',
      description: 'Giống mèo lông ngắn Mỹ, có bộ lông đen tuyền bóng mượt như báo đen mini, thân thiện.',
      id: 14,
    },
    {
      key: 'brazilian-shorthair',
      value: 'Brazilian Shorthair',
      vietnamese: 'Mèo Brazilian Shorthair',
      description: 'Giống mèo tự nhiên của Brazil, khỏe mạnh và nhanh nhẹn.',
      id: 15,
    },
    {
      key: 'british-semi-longhair',
      value: 'British Semi-longhair',
      vietnamese: 'Mèo British Semi-longhair',
      description: 'Phiên bản lông dài vừa của mèo Anh, bộ lông dày và mềm mại.',
      id: 16,
    },
    {
      key: 'british-shorthair',
      value: 'British Shorthair',
      vietnamese: 'Mèo Anh lông ngắn',
      description: 'Mèo lông ngắn Anh, nổi tiếng với thân hình chắc nịch, bộ lông dày và khuôn mặt rộng, tính cách hiền lành.',
      id: 17,
    },
    {
      key: 'british-longhair',
      value: 'British Longhair',
      vietnamese: 'Mèo Anh lông dài',
      description: 'Phiên bản lông dài của mèo Anh, tương tự British Shorthair về tính cách.',
      id: 18,
    },
    {
      key: 'burmese',
      value: 'Burmese',
      vietnamese: 'Mèo Miến Điện',
      description: 'Giống mèo lông ngắn, mềm mịn, thân thiện và tình cảm, ít rụng lông.',
      id: 19,
    },
    {
      key: 'burmilla',
      value: 'Burmilla',
      vietnamese: 'Mèo Burmilla',
      description: 'Sự kết hợp giữa Burmese và Chinchilla Persian, có bộ lông bạc lấp lánh.',
      id: 20,
    },
    {
      key: 'california-spangled',
      value: 'California Spangled',
      vietnamese: 'Mèo California Spangled',
      description: 'Giống mèo nhà có vẻ ngoài giống báo đốm, thân thiện và trung thành.',
      id: 21,
    },
    {
      key: 'chantilly-tiffany',
      value: 'Chantilly-Tiffany',
      vietnamese: 'Mèo Chantilly-Tiffany',
      description: 'Giống mèo lông dài với đôi mắt vàng và tính cách dễ chịu.',
      id: 22,
    },
    {
      key: 'chartreux',
      value: 'Chartreux',
      vietnamese: 'Mèo Chartreux',
      description: 'Giống mèo quý hiếm của Pháp, có thân hình vạm vỡ, bộ lông xám đặc trưng.',
      id: 23,
    },
    {
      key: 'chausie',
      value: 'Chausie',
      vietnamese: 'Mèo Chausie',
      description: 'Mèo lai giữa mèo rừng và mèo nhà, tính cách hòa đồng, thích chạy nhảy.',
      id: 24,
    },
    {
      key: 'cheetoh',
      value: 'Cheetoh',
      vietnamese: 'Mèo Cheetoh',
      description: 'Giống mèo lai giữa Ocicat và Bengal, có bộ lông đốm tương tự báo săn.',
      id: 25,
    },
    {
      key: 'colorpoint-shorthair',
      value: 'Colorpoint Shorthair',
      vietnamese: 'Mèo Colorpoint Shorthair',
      description: 'Giống mèo lông ngắn có điểm màu, tương tự Xiêm nhưng với nhiều màu sắc hơn.',
      id: 26,
    },
    {
      key: 'cornish-rex',
      value: 'Cornish Rex',
      vietnamese: 'Mèo Cornish Rex',
      description: 'Mèo lông ngắn, xoăn tít, ít rụng lông, năng động và thích được quan tâm.',
      id: 27,
    },
    {
      key: 'cymric',
      value: 'Cymric',
      vietnamese: 'Mèo Cymric',
      description: 'Phiên bản lông dài của Manx, nổi tiếng với việc không có đuôi hoặc đuôi rất ngắn.',
      id: 28,
    },
    {
      key: 'cyprus',
      value: 'Cyprus',
      vietnamese: 'Mèo Síp',
      description: 'Giống mèo tự nhiên từ đảo Síp, khỏe mạnh và đã tồn tại hàng ngàn năm.',
      id: 29,
    },
    {
      key: 'devon-rex',
      value: 'Devon Rex',
      vietnamese: 'Mèo Devon Rex',
      description: 'Đặc trưng bởi bộ lông xoăn mềm mại, tai lớn và tính cách tinh nghịch.',
      id: 30,
    },
    {
      key: 'donskoy',
      value: 'Donskoy',
      vietnamese: 'Mèo Donskoy',
      description: 'Mèo không lông của Nga, có thể có hoặc không có lông tơ.',
      id: 31,
    },
    {
      key: 'dragon-li',
      value: 'Dragon Li',
      vietnamese: 'Mèo Dragon Li',
      description: 'Giống mèo tự nhiên của Trung Quốc, có bộ lông vằn độc đáo.',
      id: 32,
    },
    {
      key: 'dwarf-cat',
      value: 'Dwarf cat',
      vietnamese: 'Mèo lùn',
      description: 'Các giống mèo có chân ngắn do đột biến gen, ví dụ Munchkin.',
      id: 33,
    },
    {
      key: 'egyptian-mau',
      value: 'Egyptian Mau',
      vietnamese: 'Mèo Egyptian Mau',
      description: 'Mèo lông ngắn Ai Cập, một trong số ít giống mèo nhà có đốm tự nhiên.',
      id: 34,
    },
    {
      key: 'european-shorthair',
      value: 'European Shorthair',
      vietnamese: 'Mèo lông ngắn châu Âu',
      description: 'Giống mèo nhà truyền thống của châu Âu, khỏe mạnh và thích nghi tốt.',
      id: 35,
    },
    {
      key: 'exotic-shorthair',
      value: 'Exotic Shorthair',
      vietnamese: 'Mèo Exotic Shorthair',
      description: 'Phiên bản lông ngắn của mèo Ba Tư, có khuôn mặt tịt và bộ lông dày.',
      id: 36,
    },
    {
      key: 'foldex',
      value: 'Foldex',
      vietnamese: 'Mèo Foldex',
      description: 'Giống mèo lai giữa Exotic Shorthair và Scottish Fold, có tai cụp.',
      id: 37,
    },
    {
      key: 'german-rex',
      value: 'German Rex',
      vietnamese: 'Mèo German Rex',
      description: 'Mèo lông xoăn của Đức, tương tự Cornish Rex nhưng có thân hình chắc nịch hơn.',
      id: 38,
    },
    {
      key: 'havana-brown',
      value: 'Havana Brown',
      vietnamese: 'Mèo Havana Brown',
      description: 'Giống mèo lông ngắn màu nâu chocolate, thông minh và thân thiện, có nguồn gốc từ Anh.',
      id: 39,
    },
    {
      key: 'highlander',
      value: 'Highlander',
      vietnamese: 'Mèo Highlander',
      description: 'Giống mèo lai với tai cong và đuôi ngắn, có vẻ ngoài mạnh mẽ.',
      id: 40,
    },
    {
      key: 'himalayan',
      value: 'Himalayan',
      vietnamese: 'Mèo Himalayan',
      description: 'Biến thể của mèo Ba Tư với đặc điểm màu sắc giống mèo Xiêm.',
      id: 41,
    },
    {
      key: 'japanese-bobtail',
      value: 'Japanese Bobtail',
      vietnamese: 'Mèo cụt đuôi Nhật Bản',
      description: 'Đặc trưng bởi chiếc đuôi ngắn, bông như đuôi thỏ, tính cách thân thiện.',
      id: 42,
    },
    {
      key: 'javanese',
      value: 'Javanese',
      vietnamese: 'Mèo Javanese',
      description: 'Giống mèo thanh lịch, lông dài vừa, có liên quan đến Balinese và Oriental Longhair.',
      id: 43,
    },
    {
      key: 'karelian-bobtail',
      value: 'Karelian Bobtail',
      vietnamese: 'Mèo Karelian Bobtail',
      description: 'Giống mèo đuôi ngắn của Nga, có thể có lông dài hoặc ngắn.',
      id: 44,
    },
    {
      key: 'khao-manee',
      value: 'Khao Manee',
      vietnamese: 'Mèo Khao Manee',
      description: 'Mèo trắng tinh khiết của Thái Lan, nổi tiếng với đôi mắt xanh hoặc hai màu mắt.',
      id: 45,
    },
    {
      key: 'korat',
      value: 'Korat',
      vietnamese: 'Mèo Korat',
      description: 'Giống mèo bạc của Thái Lan, mang lại may mắn, có bộ lông ngắn màu xanh xám.',
      id: 46,
    },
    {
      key: 'korean-bobtail',
      value: 'Korean Bobtail',
      vietnamese: 'Mèo Korean Bobtail',
      description: 'Giống mèo đuôi ngắn của Hàn Quốc.',
      id: 47,
    },
    {
      key: 'korn-ja',
      value: 'Korn Ja',
      vietnamese: 'Mèo Korn Ja',
      description: 'Giống mèo đen của Thái Lan, được coi là may mắn.',
      id: 48,
    },
    {
      key: 'kurilian-bobtail',
      value: 'Kurilian Bobtail',
      vietnamese: 'Mèo Kurilian Bobtail',
      description: 'Giống mèo đuôi ngắn của quần đảo Kuril, có bộ lông dày và tính cách hoạt bát.',
      id: 49,
    },
    {
      key: 'laperm',
      value: 'LaPerm',
      vietnamese: 'Mèo LaPerm',
      description: 'Đặc trưng bởi bộ lông xoăn gợn sóng, thân thiện và thích nghi tốt.',
      id: 50,
    },
    {
      key: 'lykoi',
      value: 'Lykoi',
      vietnamese: 'Mèo Lykoi',
      description: 'Mèo có vẻ ngoài giống ma sói do đột biến gen, lông ngắn thưa quanh mắt, mũi, tai.',
      id: 51,
    },
    {
      key: 'maine-coon',
      value: 'Maine Coon',
      vietnamese: 'Mèo Maine Coon',
      description: 'Giống mèo nhà lớn nhất, lông dài, thân thiện và có kỹ năng săn mồi tốt.',
      id: 52,
    },
    {
      key: 'manx',
      value: 'Manx',
      vietnamese: 'Mèo Manx',
      description: 'Giống mèo không đuôi hoặc đuôi rất ngắn, có nguồn gốc từ đảo Man.',
      id: 53,
    },
    {
      key: 'mekong-bobtail',
      value: 'Mekong Bobtail',
      vietnamese: 'Mèo Mekong Bobtail',
      description: 'Giống mèo đuôi ngắn có điểm màu, phổ biến ở Đông Nam Á.',
      id: 54,
    },
    {
      key: 'minskin',
      value: 'Minskin',
      vietnamese: 'Mèo Minskin',
      description: 'Sự kết hợp giữa Munchkin và Sphynx, có chân ngắn và bộ lông thưa thớt.',
      id: 55,
    },
    {
      key: 'munchkin',
      value: 'Munchkin',
      vietnamese: 'Mèo Munchkin',
      description: 'Giống mèo chân cực ngắn, đáng yêu và tinh nghịch.',
      id: 56,
    },
    {
      key: 'nebelung',
      value: 'Nebelung',
      vietnamese: 'Mèo Nebelung',
      description: 'Phiên bản lông dài của Russian Blue, có bộ lông màu xanh xám.',
      id: 57,
    },
    {
      key: 'napoleon',
      value: 'Napoleon',
      vietnamese: 'Mèo Napoleon',
      description: 'Sự kết hợp giữa Persian và Munchkin, có chân ngắn và khuôn mặt tịt.',
      id: 58,
    },
    {
      key: 'norwegian-forest-cat',
      value: 'Norwegian Forest cat',
      vietnamese: 'Mèo rừng Na Uy',
      description: 'Giống mèo lớn, lông dài, thích nghi tốt với khí hậu lạnh.',
      id: 59,
    },
    {
      key: 'ocicat',
      value: 'Ocicat',
      vietnamese: 'Mèo Ocicat',
      description: 'Giống mèo có vẻ ngoài giống mèo rừng (ocelot) nhưng là mèo nhà thuần chủng, thân thiện.',
      id: 60,
    },
    {
      key: 'ojos-azules',
      value: 'Ojos Azules',
      vietnamese: 'Mèo Ojos Azules',
      description: 'Giống mèo hiếm với đôi mắt xanh lam đặc trưng.',
      id: 61,
    },
    {
      key: 'oregon-rex',
      value: 'Oregon Rex',
      vietnamese: 'Mèo Oregon Rex',
      description: 'Giống mèo lông xoăn đã tuyệt chủng.',
      id: 62,
    },
    {
      key: 'oriental-bicolor',
      value: 'Oriental Bicolor',
      vietnamese: 'Mèo Oriental Bicolor',
      description: 'Biến thể hai màu của mèo Oriental Shorthair.',
      id: 63,
    },
    {
      key: 'oriental-shorthair',
      value: 'Oriental Shorthair',
      vietnamese: 'Mèo Oriental Shorthair',
      description: 'Giống mèo thanh mảnh, tai lớn và tính cách hoạt bát, có nhiều màu sắc.',
      id: 64,
    },
    {
      key: 'oriental-longhair',
      value: 'Oriental Longhair',
      vietnamese: 'Mèo Oriental Longhair',
      description: 'Phiên bản lông dài của Oriental Shorthair.',
      id: 65,
    },
    {
      key: 'perfold',
      value: 'PerFold',
      vietnamese: 'Mèo PerFold',
      description: 'Sự kết hợp giữa Persian và Scottish Fold.',
      id: 66,
    },
    {
      key: 'persian-modern',
      value: 'Persian (Modern Persian Cat)',
      vietnamese: 'Mèo Ba Tư (Hiện đại)',
      description: 'Mèo Ba Tư mặt tịt, có khuôn mặt phẳng đặc trưng và bộ lông dài dày.',
      id: 67,
    },
    {
      key: 'persian-traditional',
      value: 'Persian (Traditional Persian Cat)',
      vietnamese: 'Mèo Ba Tư (Truyền thống)',
      description: 'Mèo Ba Tư với khuôn mặt ít tịt hơn, gần với vẻ ngoài tự nhiên hơn.',
      id: 68,
    },
    {
      key: 'peterbald',
      value: 'Peterbald',
      vietnamese: 'Mèo Peterbald',
      description: 'Giống mèo không lông hoặc lông rất ngắn, có nguồn gốc từ Nga.',
      id: 69,
    },
    {
      key: 'pixie-bob',
      value: 'Pixie-bob',
      vietnamese: 'Mèo Pixie-bob',
      description: 'Mèo có vẻ ngoài giống linh miêu đuôi cụt, tính cách thân thiện và thông minh.',
      id: 70,
    },
    {
      key: 'raas',
      value: 'Raas',
      vietnamese: 'Mèo Raas',
      description: 'Giống mèo tự nhiên từ Indonesia.',
      id: 71,
    },
    {
      key: 'ragamuffin',
      value: 'Ragamuffin',
      vietnamese: 'Mèo Ragamuffin',
      description: 'Giống mèo lớn, lông dài, thân thiện và đáng yêu.',
      id: 72,
    },
    {
      key: 'ragdoll',
      value: 'Ragdoll',
      vietnamese: 'Mèo Ragdoll',
      description: 'Giống mèo lớn, tính cách hiền lành, dễ ôm, thường rũ người khi được bế.',
      id: 73,
    },
    {
      key: 'russian-blue',
      value: 'Russian Blue',
      vietnamese: 'Mèo Nga xanh',
      description: 'Mèo lông ngắn Nga, có bộ lông xanh xám dày và đôi mắt xanh lục bảo, hiền lành.',
      id: 74,
    },
    {
      key: 'russian-white-black-tabby',
      value: 'Russian White, Black and Tabby',
      vietnamese: 'Mèo Nga trắng, đen và vằn',
      description: 'Các biến thể màu sắc của mèo Nga.',
      id: 75,
    },
    {
      key: 'sam-sawet',
      value: 'Sam Sawet',
      vietnamese: 'Mèo Sam Sawet',
      description: 'Một giống mèo của Thái Lan.',
      id: 76,
    },
    {
      key: 'savannah',
      value: 'Savannah',
      vietnamese: 'Mèo Savannah',
      description: 'Giống mèo lai giữa mèo nhà và mèo rừng châu Phi, lớn nhất trong các giống mèo lai.',
      id: 77,
    },
    {
      key: 'scottish-fold',
      value: 'Scottish Fold',
      vietnamese: 'Mèo Scottish Fold',
      description: 'Đặc trưng bởi đôi tai cụp độc đáo, tính cách điềm tĩnh và đáng yêu.',
      id: 78,
    },
    {
      key: 'selkirk-rex',
      value: 'Selkirk Rex',
      vietnamese: 'Mèo Selkirk Rex',
      description: 'Mèo lông xoăn với bộ lông dày và mềm mại.',
      id: 79,
    },
    {
      key: 'serengeti',
      value: 'Serengeti',
      vietnamese: 'Mèo Serengeti',
      description: 'Giống mèo lai giữa Bengal và Oriental, có vẻ ngoài giống mèo rừng nhưng không có gen hoang dã.',
      id: 80,
    },
    {
      key: 'serrade-petit',
      value: 'Serrade petit',
      vietnamese: 'Mèo Serrade petit',
      description: 'Một giống mèo hiếm của Pháp.',
      id: 81,
    },
    {
      key: 'siamese',
      value: 'Siamese',
      vietnamese: 'Mèo Xiêm',
      description: 'Giống mèo lông ngắn có điểm màu đặc trưng, giọng nói to và tính cách tình cảm.',
      id: 82,
    },
    {
      key: 'siberian',
      value: 'Siberian',
      vietnamese: 'Mèo Siberian',
      description: 'Mèo lông dài của Siberia, có bộ lông dày và không gây dị ứng.',
      id: 83,
    },
    {
      key: 'singapura',
      value: 'Singapura',
      vietnamese: 'Mèo Singapura',
      description: 'Một trong những giống mèo nhỏ nhất thế giới, có bộ lông màu nâu sepia.',
      id: 84,
    },
    {
      key: 'snowshoe',
      value: 'Snowshoe',
      vietnamese: 'Mèo Snowshoe',
      description: 'Sự kết hợp giữa Xiêm và American Shorthair, có điểm màu và bàn chân trắng.',
      id: 85,
    },
    {
      key: 'sokoke',
      value: 'Sokoke',
      vietnamese: 'Mèo Sokoke',
      description: 'Giống mèo tự nhiên từ Kenya, có bộ lông vằn độc đáo.',
      id: 86,
    },
    {
      key: 'somali',
      value: 'Somali',
      vietnamese: 'Mèo Somali',
      description: 'Phiên bản lông dài của Abyssinian, có bộ lông màu cam đỏ.',
      id: 87,
    },
    {
      key: 'sphynx',
      value: 'Sphynx',
      vietnamese: 'Mèo Sphynx',
      description: 'Mèo không lông với làn da nhăn nheo, tính cách tình cảm và thích được vuốt ve.',
      id: 88,
    },
    {
      key: 'suphalak',
      value: 'Suphalak',
      vietnamese: 'Mèo Suphalak',
      description: 'Giống mèo của Thái Lan, có bộ lông màu nâu đỏ.',
      id: 89,
    },
    {
      key: 'thai',
      value: 'Thai',
      vietnamese: 'Mèo Thái',
      description: 'Giống mèo tự nhiên của Thái Lan, tương tự Xiêm cổ điển.',
      id: 90,
    },
    {
      key: 'thai-lilac',
      value: 'Thai Lilac',
      vietnamese: 'Mèo Thai Lilac',
      description: 'Biến thể màu tím của mèo Korat.',
      id: 91,
    },
    {
      key: 'tonkinese',
      value: 'Tonkinese',
      vietnamese: 'Mèo Tonkinese',
      description: 'Sự kết hợp giữa Xiêm và Burmese, có màu lông trung gian.',
      id: 92,
    },
    {
      key: 'toyger',
      value: 'Toyger',
      vietnamese: 'Mèo Toyger',
      description: 'Mèo nhà được lai tạo để trông giống hổ đồ chơi, có bộ lông vằn.',
      id: 93,
    },
    {
      key: 'turkish-angora',
      value: 'Turkish Angora',
      vietnamese: 'Mèo Turkish Angora',
      description: 'Giống mèo lông dài thanh lịch của Thổ Nhĩ Kỳ, thường có màu trắng.',
      id: 94,
    },
    {
      key: 'turkish-van',
      value: 'Turkish Van',
      vietnamese: 'Mèo Turkish Van',
      description: 'Mèo lông dài của Thổ Nhĩ Kỳ, thích bơi lội và có đốm màu trên đầu và đuôi.',
      id: 95,
    },
    {
      key: 'ukrainian-levkoy',
      value: 'Ukrainian Levkoy',
      vietnamese: 'Mèo Ukrainian Levkoy',
      description: 'Giống mèo không lông với tai cụp, có nguồn gốc từ Ukraine.',
      id: 96,
    },
  ]

  return {
    breeds,
  }
}
