export function useCatBreed() {
  const breeds = [
    { key: 'abyssinian', value: 'Abyssinian' },
    { key: 'aegean', value: 'Aegean' },
    { key: 'american-curl', value: 'American Curl' },
    { key: 'american-bobtail', value: 'American Bobtail' },
    { key: 'american-shorthair', value: 'American Shorthair' },
    { key: 'american-wirehair', value: 'American Wirehair' },
    { key: 'arabian-mau', value: 'Arabian Mau' },
    { key: 'australian-mist', value: 'Australian Mist' },
    { key: 'asian', value: 'Asian' },
    { key: 'asian-semi-longhair', value: 'Asian Semi-longhair' },
    { key: 'balinese', value: 'Balinese' },
    { key: 'bambino', value: 'Bambino' },
    { key: 'bengal', value: 'Bengal' },
    { key: 'birman', value: 'Birman' },
    { key: 'bombay', value: 'Bombay' },
    { key: 'brazilian-shorthair', value: 'Brazilian Shorthair' },
    { key: 'british-semi-longhair', value: 'British Semi-longhair' },
    { key: 'british-shorthair', value: 'British Shorthair' },
    { key: 'british-longhair', value: 'British Longhair' },
    { key: 'burmese', value: 'Burmese' },
    { key: 'burmilla', value: 'Burmilla' },
    { key: 'california-spangled', value: 'California Spangled' },
    { key: 'chantilly-tiffany', value: 'Chantilly-Tiffany' },
    { key: 'chartreux', value: 'Chartreux' },
    { key: 'chausie', value: 'Chausie' },
    { key: 'cheetoh', value: 'Cheetoh' },
    { key: 'colorpoint-shorthair', value: 'Colorpoint Shorthair' },
    { key: 'cornish-rex', value: 'Cornish Rex' },
    { key: 'cymric', value: 'Cymric' },
    { key: 'cyprus', value: 'Cyprus' },
    { key: 'devon-rex', value: 'Devon Rex' },
    { key: 'donskoy', value: 'Donskoy' },
    { key: 'dragon-li', value: 'Dragon Li' },
    { key: 'dwarf-cat', value: 'Dwarf cat' },
    { key: 'egyptian-mau', value: 'Egyptian Mau' },
    { key: 'european-shorthair', value: 'European Shorthair' },
    { key: 'exotic-shorthair', value: 'Exotic Shorthair' },
    { key: 'foldex', value: 'Foldex' },
    { key: 'german-rex', value: 'German Rex' },
    { key: 'havana-brown', value: 'Havana Brown' },
    { key: 'highlander', value: 'Highlander' },
    { key: 'himalayan', value: 'Himalayan' },
    { key: 'japanese-bobtail', value: 'Japanese Bobtail' },
    { key: 'javanese', value: 'Javanese' },
    { key: 'karelian-bobtail', value: 'Karelian Bobtail' },
    { key: 'khao-manee', value: 'Khao Manee' },
    { key: 'korat', value: 'Korat' },
    { key: 'korean-bobtail', value: 'Korean Bobtail' },
    { key: 'korn-ja', value: 'Korn Ja' },
    { key: 'kurilian-bobtail', value: 'Kurilian Bobtail' },
    { key: 'laperm', value: 'LaPerm' },
    { key: 'lykoi', value: 'Lykoi' },
    { key: 'maine-coon', value: 'Maine Coon' },
    { key: 'manx', value: 'Manx' },
    { key: 'mekong-bobtail', value: 'Mekong Bobtail' },
    { key: 'minskin', value: 'Minskin' },
    { key: 'munchkin', value: 'Munchkin' },
    { key: 'nebelung', value: 'Nebelung' },
    { key: 'napoleon', value: 'Napoleon' },
    { key: 'norwegian-forest-cat', value: 'Norwegian Forest cat' },
    { key: 'ocicat', value: 'Ocicat' },
    { key: 'ojos-azules', value: 'Ojos Azules' },
    { key: 'oregon-rex', value: 'Oregon Rex' },
    { key: 'oriental-bicolor', value: 'Oriental Bicolor' },
    { key: 'oriental-shorthair', value: 'Oriental Shorthair' },
    { key: 'oriental-longhair', value: 'Oriental Longhair' },
    { key: 'perfold', value: 'PerFold' },
    { key: 'persian-modern', value: 'Persian (Modern Persian Cat)' },
    { key: 'persian-traditional', value: 'Persian (Traditional Persian Cat)' },
    { key: 'peterbald', value: 'Peterbald' },
    { key: 'pixie-bob', value: 'Pixie-bob' },
    { key: 'raas', value: 'Raas' },
    { key: 'ragamuffin', value: 'Ragamuffin' },
    { key: 'ragdoll', value: 'Ragdoll' },
    { key: 'russian-blue', value: 'Russian Blue' },
    { key: 'russian-white-black-tabby', value: 'Russian White, Black and Tabby' },
    { key: 'sam-sawet', value: 'Sam Sawet' },
    { key: 'savannah', value: 'Savannah' },
    { key: 'scottish-fold', value: 'Scottish Fold' },
    { key: 'selkirk-rex', value: 'Selkirk Rex' },
    { key: 'serengeti', value: 'Serengeti' },
    { key: 'serrade-petit', value: 'Serrade petit' },
    { key: 'siamese', value: 'Siamese' },
    { key: 'siberian', value: 'Siberian' },
    { key: 'singapura', value: 'Singapura' },
    { key: 'snowshoe', value: 'Snowshoe' },
    { key: 'sokoke', value: 'Sokoke' },
    { key: 'somali', value: 'Somali' },
    { key: 'sphynx', value: 'Sphynx' },
    { key: 'suphalak', value: 'Suphalak' },
    { key: 'thai', value: 'Thai' },
    { key: 'thai-lilac', value: 'Thai Lilac' },
    { key: 'tonkinese', value: 'Tonkinese' },
    { key: 'toyger', value: 'Toyger' },
    { key: 'turkish-angora', value: 'Turkish Angora' },
    { key: 'turkish-van', value: 'Turkish Van' },
    { key: 'ukrainian-levkoy', value: 'Ukrainian Levkoy' },
  ]

  return {
    breeds,
  }
}
